Ensure existing Faker methods can be called
Before this change, existing Faker methods would fail once the
`MarketDataProvider` had been added:

```python
fake = Faker()
fake.add_provider(MarketDataProvider)
random_str = fake.lexify("???????")
```

```
Traceback (most recent call last):
  File "faker_marketdata/tests/test_marketdata.py", line 74, in test_existing_fake_methods_still_work
    random_str = fake.lexify("???????")
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faker/providers/__init__.py", line 633, in lexify
    return _re_qm.sub(lambda x: self.random_element(letters), text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faker/providers/__init__.py", line 633, in <lambda>
    return _re_qm.sub(lambda x: self.random_element(letters), text)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faker/providers/__init__.py", line 545, in random_element
    return self.random_elements(elements, length=1)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faker/providers/__init__.py", line 493, in random_elements
    return fn(
           ^^^
  File "venv/lib/python3.11/site-packages/faker/utils/distribution.py", line 84, in choices_distribution
    uniform_sample = random_sample(random=random)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faker/utils/distribution.py", line 13, in random_sample
    return random.uniform(0.0, 1.0)
           ^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'uniform'

```

I've removed the `__init__` method from the `MarketDataProvider`
because Faker will take care of initializing the provider when the class
is passed to `add_provider`, and updated the provider to use the base
class' random number generator.

I've also reduced the number of iterations in the unit tests just to
speed things up, but I'm happy to revert that if you think the
extra iterations are necessary.